<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PAKU-BLR-01" ignored="0" name="Test retrying logic at class level" tests="27" failures="5" timestamp="21 Oct 2022 08:07:36 GMT" time="118.191" errors="0">
  <testcase name="test" time="0.018" classname="TestNgRevision.MyTestcase2"/>
  <testcase name="test1" time="0.008" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TestNgRevision.MyTestcase2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestNgRevision.MyTestcase2.test1(MyTestcase2.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.004" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="TestNgRevision.MyTestcase2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestNgRevision.MyTestcase2.test2(MyTestcase2.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="TestNgRevision.MyTestcase2">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.003" classname="TestNgRevision.MyTestcase2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestNgRevision.MyTestcase2.test3(MyTestcase2.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="titleTest" time="0.016" classname="TestNgRevision.GoogleAnnotationTesting_2"/>
  <testcase name="imageLinkTest" time="0.492" classname="TestNgRevision.GoogleAnnotationTesting_2"/>
  <testcase name="logoTest" time="0.261" classname="TestNgRevision.GoogleAnnotationTesting_2"/>
  <testcase name="A" time="0.003" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <skipped/>
  </testcase> <!-- A -->
  <testcase name="A" time="0.002" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <skipped/>
  </testcase> <!-- A -->
  <testcase name="A" time="0.003" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <skipped/>
  </testcase> <!-- A -->
  <testcase name="A" time="0.002" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestNgRevision.GoogleAnnotationTesting_2.A(GoogleAnnotationTesting_2.java:59)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="B" time="0.001" classname="TestNgRevision.GoogleAnnotationTesting_2"/>
  <testcase name="C" time="0.003" classname="TestNgRevision.GoogleAnnotationTesting_2"/>
  <testcase name="D" time="0.002" classname="TestNgRevision.GoogleAnnotationTesting_2"/>
  <testcase name="linkTest" time="0.021" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <skipped/>
  </testcase> <!-- linkTest -->
  <testcase name="linkTest" time="0.022" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <skipped/>
  </testcase> <!-- linkTest -->
  <testcase name="linkTest" time="0.025" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <skipped/>
  </testcase> <!-- linkTest -->
  <testcase name="linkTest" time="0.013" classname="TestNgRevision.GoogleAnnotationTesting_2">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNgRevision.GoogleAnnotationTesting_2.linkTest() didn&amp;apos;t finish within the time-out 10">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNgRevision.GoogleAnnotationTesting_2.linkTest() didn't finish within the time-out 10
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.InterruptedException.<init>(InterruptedException.java:57)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler$$Lambda$32/754177595.execute(Unknown Source)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent$$Lambda$236/1260467793.execute(Unknown Source)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.Filter$$Lambda$33/1776374725.execute(Unknown Source)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent$$Lambda$236/1260467793.execute(Unknown Source)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.Filter$$Lambda$33/1776374725.execute(Unknown Source)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
	at TestNgRevision.GoogleAnnotationTesting_2.linkTest(GoogleAnnotationTesting_2.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- linkTest -->
</testsuite> <!-- Test retrying logic at class level -->
